# Generated by Django 5.1.2 on 2024-11-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0002_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='crew',
            field=models.BooleanField(default=False),
        ),
    ]
